### ISSUE TITLE
SyntaxError: Unexpected tokens in JSON at position 422

### ISSUE THREAD

**Issue by ozeliger** [modzy/modzy-jupyter-notebook-samples#2]
Hi, 

I receive this error when trying to load [this notebook](https://github.com/modzy/modzy-jupyter-notebook-samples/blob/main/python-sdk-inference/Submitting%20Jobs%20with%20Python%20SDK.ipynb). Apparently, it hasn't been rendered correctly. 

I have tried opening this on Google Colab, VSCode, a local Jupyter Notebook instance, but each time I receive this error. Kindly correct this as soon as possible :)

Thanks,
-O

**Comment by ozeliger** [comment]
@bmunday3 @cbatis @caradoxical

**Comment by bmunday3-zz** [comment]
@ozeliger thank you for raising this issue!

This is now fixed and is rendered properly. You should now be able to run this [notebook](https://github.com/modzy/modzy-jupyter-notebook-samples/blob/main/python-sdk-inference/Submitting%20Jobs%20with%20Python%20SDK%20-%20Automobile%20Classification.ipynb).
